# Generated by Django 4.2.7 on 2023-11-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_carslistmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100, verbose_name='Название машины Афиша')),
                ('time', models.PositiveIntegerField(verbose_name='Пробег машины в км')),
                ('cost', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.URLField()),
            ],
        ),
    ]
