# Generated by Django 4.2.7 on 2023-11-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_afisha_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afisha',
            old_name='time',
            new_name='drive',
        ),
    ]
